name: CI Pipeline

on:
  pull_request:
    types: [ opened, edited ]
    branches: [ "main", "development" ]
  push:
    branches: [ "development" ]

jobs:
  build-backend:
    name: Build Java Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check if it's a documentation change (README.md)
        if: |
          contains(github.event.pull_request.files, 'README.md') &&
          github.event.pull_request.changed_files == 1
        run: |
          echo "This PR only changes README.md. Merging..."
          gh pr merge ${{ github.event.pull_request.number }} --merge

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Ensure Java 21
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Build and package the backend
        run: mvn package
